name: Tests
on:
  pull_request:
  push:
    branches:
      - develop
      - release/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unit-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test and Create Coverage Report
        run: |
          make test-unit-cover
        if: env.GIT_DIFF
      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
        if: env.GIT_DIFF

  test-importer:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: test-importer
        run: |
          make test-import
        if: env.GIT_DIFF

  test-rpc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test rpc endpoint
        run: |
          make test-rpc
        if: env.GIT_DIFF

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Test simulation nondeterminism
        run: |
          make test-sim-nondeterminism
        if: env.GIT_DIFF

  test-sim-random-genesis-fast:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Test simulation with random genesis
        run: |
          make test-sim-random-genesis-fast
        if: env.GIT_DIFF

  test-sim-import-export:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Simulation of import and export genesis
        run: |
          make test-sim-import-export
        if: env.GIT_DIFF

  test-sim-after-import:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Test simulation after import
        run: |
          make test-sim-after-import
        if: env.GIT_DIFF
